const DOMSelectors = {
    title: document.querySelector(".second"),
    card: document.querySelector(".card"),
    link: document.querySelectorAll(".link"),
    form1: document.querySelector(".Types"),
    form2: document.querySelector(".Berries"),
    formball: document.querySelector(".Ball"),
    form3: document.querySelector(".Region"),
    form: document.querySelector(".Main"),
    logo:document.querySelector(".logo"),
    buttonFlip: document.querySelector("footer"),
    form4: document.querySelector(".next1"),
    form5: document.querySelector(".next2"),
    form6: document.querySelector(".next3"),
    form7: document.querySelector(".next4"),
    search: document.querySelector("#form"),
    input: document.querySelector("#pokemon"),
    h1:document.querySelectorAll("h1"),
    h2: document.querySelectorAll(".name"),
    h3:document.querySelectorAll(".type"),
    h4:document.querySelectorAll(".veganornot"),
    h5:document.querySelectorAll(".price"),
    img: document.querySelectorAll(".card-img"),
    gallery: document.querySelector(".flex-container"),
    button:document.getElementById("#btn"),
    text:document.querySelector("#text"),
    empty:document.querySelector(".nothing"),
    pic:document.querySelector(".img"),
    theme:document.querySelector(".Mystic"),
    theme2:document.querySelector(".Instinct"),
    theme3:document.querySelector(".Valor"),
    /* point:document.querySelectorAll(".point"), //gets all instances of this
    pointTwo:document.getElementById("pointTwo"), */
  };

  export{DOMSelectors};